### PR TITLE
add defhook macro

### PR DESCRIPTION
**Pull request by roman01la**
Adding `defhook` macro for Hooks definition.

```clojure
;; before
(defn use-element-size []
  (let [ref (uix/use-ref)]
    ...))

;; now
(defhook use-element-size []
  (let [ref (uix/use-ref)]
    ...))
```

### Linting the rules of hooks

`defui` macro already takes care of linting component's body to make sure that no hooks are called in a loop or a condition or a callback. Now with custom (higher level, created in application code) hooks it's not possible to lint them since they are normal `defn`s. `defhook` macro takes care of this part by emitting same `defn` but additionally linting body of the function.

#### Why not use clj-kondo for that?

It's true that a general purpose linter could be used for such a task, which would almost entirely remove a need for macros. But there are multiple road bumps that stop us from going this route.

- clj-kondo exposes a limited amount of information about parsed code, which is not enough for building a linting rule to cover The Rules of Hooks
- clj-kondo is a third-party tool that has to be installed and configured on CI and developer's IDEs
- while clj-kondo integrates into IDEs and can be used to fail production build on CI, it doesn't integrate with build tooling and runtime, which has a number of benefits that we'll discuss in a second

### Duck typing

Original ESLint plugin for React Hooks considers any function starting with `use[A-Z]` to be a hook. While this works fine for most cases, we also have generic functions that are prefixed with `use`. This kind of duck typing introduces false positives to the linter and sets a requirement on the code base that only React Hooks functions are allowed to be named with `use` prefix, see example below.

https://codesandbox.io/s/relaxed-tharp-2bq4om?file=/src/App.js
Screenshot 2022-06-09 at 1 04 55 PM

## Benefits

- Custom hooks can be linted
- Linting doesn't depend on your dev setup
- Linting errors are reported in production builds and dev, both in terminal and UI
- Generic function can still have `use` prefix

## Downsides

- A developer has to remember to use `defhook` when creating a hook
    - This can be fixed by checking that custom hooks (only from application code, not 3rd party libraries) called in UIx components are defined via `defhook`
- No errors reported to IDE
- Only actual errors reporting can be implemented, not warnings that are usually considered optional suggestions and reported via IDE UI

## Alternative approaches

- Extend or contribute to clj-kondo to enable access to entire AST tree
- Build our own linter (probably the best option, but it's a larger project)

## Prior art

`defhook` macro in Helix

### CODE REVIEW

**Comment by esender** [comment]
Both options `defn` and `defhook` look good for me. 

I don't think it is some kind of problem to use `defhook` in the code I mean there is no difference from the developer perspective except linting bonuses.

Even more for me, it is more like aligning with the uix library. We will have a special macro for ui component and hook so it will help separate contexts at a glance. And I don't think it will somehow affect newcomers learning curve in general. Moreover, I think it will attract attention to hooks in time of reviewing code, which is good as hooks become one of the important parts of development.

**Comment by benrodenhaeuser** [comment]
I think this is very elegant. 

There is a downside in that it could constrain our options when using the Moira library. In Moira, there is the concept of dependencies of a module, which are things exported by other modules. I think it would be quite natural to have one module export a hook. 

```clojure
{:module-1 {:export use-bar ; use-bar is a hook
            ...}}
```

But for this, the macro approach doesn't work (or am I missing something?)

Or could we wrap the hook in a function somehow for this purpose? 

```clojure
(defhook use-bar [] ...)

(defn use-bar-fn []
  (use-bar))
```

**Comment by roman01la** [comment]
@benrodenhaeuser `defhook` would create a `defn`, so it's still possible to pass around the value by reference since it's a function, is that what you are asking about? The macro part of `defhook` is just for linting the body of a hook and marking the `defn` as "the hook", here https://github.com/pitch-io/uix/pull/66/files#diff-558caf177409d231d0fe74b1f1abf03074d062c866e22af539c46ad944a8fcb5R92-R94

**Comment by benrodenhaeuser** [comment]
> it's still possible to pass around the value by reference since it's a function, is that what you are asking about? 

Yes, exactly, that was my worry that it would not be possible to pass it around. But apparently I was simply confusing things here. Even better!

**Comment by g7s** [comment]
The rationale for using a macro to define and lint hooks makes sense to me 👍. One thing that I'm not sure I understood from the description is the level of those linting errors. When you say only actual errors reporting can be implemented does that mean that all linting errors will throw exceptions? If yes, will there be any mechanism to silence/skip such errors?

**Comment by accounts-pitch-io** [comment]
master:
React 329ms
UIx 615ms 1.9x
Reagent 911ms 2.8x


PR:
React 321ms
UIx 507ms 1.6x
Reagent 906ms 2.8x

**Comment by accounts-pitch-io** [comment]
master:
React 329ms
UIx 615ms 1.9x
Reagent 911ms 2.8x


PR:
React 308ms
UIx 497ms 1.6x
Reagent 922ms 3x

**Comment by accounts-pitch-io** [comment]
master:
React 329ms
UIx 615ms 1.9x
Reagent 911ms 2.8x


PR:
React 300ms
UIx 499ms 1.7x
Reagent 906ms 3x

**Pull request closed without merging**
