### PR TITLE
Upgrade to React 18 APIs

### PR DESCRIPTION
**Pull request by roman01la**
Includes new hooks and ReactDOM API

### CODE REVIEW

**Comment by accounts-pitch-io** [comment]
master:
React 337ms
UIx 560ms 1.7x
Reagent 899ms 2.7x


PR:
React 352ms
UIx 684ms 1.9x
Reagent 1110ms 3.2x

**Comment by accounts-pitch-io** [comment]
master:
React 337ms
UIx 560ms 1.7x
Reagent 899ms 2.7x


PR:
React 306ms
UIx 523ms 1.7x
Reagent 854ms 2.8x

**Comment by accounts-pitch-io** [comment]
master:
React 331ms
UIx 564ms 1.7x
Reagent 919ms 2.8x


PR:
React 288ms
UIx 475ms 1.6x
Reagent 855ms 3x

**Comment by accounts-pitch-io** [comment]
master:
React 331ms
UIx 564ms 1.7x
Reagent 919ms 2.8x


PR:
React 292ms
UIx 481ms 1.6x
Reagent 866ms 3x

**Comment by ovistoica** [comment]
Shouldn't this include a change in the `Interop-with-reagent.md` docs since the `useSyncExternalStore` is part of the React 18 api?

image

**Comment by roman01la** [comment]
@ovistoica Yes, it should. But this PR is not gonna be merged yet, I haven't reviewed it in a while.

**Comment by ai212983** [comment]
Any progress on this?

**Comment by roman01la** [comment]
The upgrade to v18 will done once Pitch has adopted v18, this will take some time. Maybe sooner than later.

**Pull request merged**
