### PR TITLE
React v19 APIs

### PR DESCRIPTION
**Pull request by roman01la**
Adding new APIs listed in https://react.dev/blog/2024/04/25/react-19

### CODE REVIEW

**Comment by accounts-pitch-io** [comment]
master:
react x 11468 ops/s, elapsed 872ms
uix x 7981 ops/s, elapsed 1253ms
helix x 7452 ops/s, elapsed 1342ms
reagent x 5342 ops/s, elapsed 1872ms


PR:
react x 13123 ops/s, elapsed 762ms
uix x 9814 ops/s, elapsed 1019ms
helix x 9259 ops/s, elapsed 1080ms
reagent x 6098 ops/s, elapsed 1640ms

**Comment by accounts-pitch-io** [comment]
master:
react x 11848 ops/s, elapsed 844ms
uix x 8977 ops/s, elapsed 1114ms
helix x 8532 ops/s, elapsed 1172ms
reagent x 6406 ops/s, elapsed 1561ms


PR:
react x 11723 ops/s, elapsed 853ms
uix x 9183 ops/s, elapsed 1089ms
helix x 7375 ops/s, elapsed 1356ms
reagent x 5192 ops/s, elapsed 1926ms

**Comment by orestis** [comment]
Should this use the new jsx-transform? The react 19 upgrade guide says that [it's now required](https://react.dev/blog/2024/04/25/react-19-upgrade-guide)

**Comment by roman01la** [comment]
> Should this use the new jsx-transform? The react 19 upgrade guide says that [it's now required](https://react.dev/blog/2024/04/25/react-19-upgrade-guide)

Not sure, I tested with v19 and haven’t seen the warning. Will take another look, thanks for pointing out

**Comment by accounts-pitch-io** [comment]
master:
react x 10753 ops/s, elapsed 930ms
uix x 7955 ops/s, elapsed 1257ms
helix x 7179 ops/s, elapsed 1393ms
reagent x 4950 ops/s, elapsed 2020ms


PR:
react x 11723 ops/s, elapsed 853ms
uix x 8190 ops/s, elapsed 1221ms
helix x 8137 ops/s, elapsed 1229ms
reagent x 5373 ops/s, elapsed 1861ms

**Pull request merged**
